CLASSPATH=/swi40/jan/src/openrdf/build/lib/sesame.jar

CLASS=	SesameTest.class \
	SesameAddData.class

all:	$(CLASS)

SesameTest.class:	SesameTest.java
	javac -classpath $(CLASSPATH) $<
	
SesameAddData.class:	SesameAddData.java
	javac -classpath $(CLASSPATH) $<
